FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-virtualenv \
    git \
    wget \
    unzip \
    openjdk-17-jdk \
    ccache \
    autoconf \
    libtool \
    libssl-dev \
    libltdl-dev \
    pkg-config \
    libffi-dev \
    libncurses-dev \
    zlib1g-dev \
    curl \
    libc6-dev-i386 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV USE_SDK_WRAPPER=0

RUN pip3 install --upgrade pip setuptools virtualenv
RUN pip3 install buildozer cython

WORKDIR /app

CMD ["bash", "-c", "printf 'y\\n' | buildozer android debug"]
